"""VERDANT extension layer for the original Indev 20100223 foundation.

This package intentionally stays separate from the original Minecraft codebase.
It provides a minimal no-op integration boundary for future features that expand
or replace systems in the legacy foundation without rewriting the working game.
"""

from .config import VERDANT_CONFIG
from .version import __version__, __build__, __release_name__
from .hooks import VerdantHooks
from .world.state import VerdantWorldState
from .world.clock import VerdantSimulationClock
from .world.queries import VerdantWorldQueryBoundary
from .world.persistence import VerdantStatePersistence
from .simulation.system import VerdantSystem
from .simulation.manager import VerdantSimulationManager
from .environment import VerdantBiomeDefinition, VerdantBiomeResolver, VerdantClimateSystem, VerdantWorldSeed
from .water import (
    VerdantMoistureState,
    VerdantWaterSystem,
    get_soil_moisture,
    get_surface_water_presence,
    get_water_proximity,
    get_water_influence,
    is_near_water,
    get_moisture_state,
)
from .ecology import (
    VerdantVegetationState,
    VerdantEcologySystem,
    get_vegetation_state,
    get_growth_potential,
    get_vegetation_health,
    get_environmental_stress,
    get_fertility,
    get_season_modifier,
    get_current_season,
    get_season_progress,
    is_growth_favorable,
)
from .creatures import (
    VerdantCreatureState,
    VerdantHabitatEvaluator,
    VerdantBehaviorContext,
    VerdantCreatureSystem,
    get_creature_state,
    get_habitat_score,
    get_food_suitability,
    get_water_access,
    get_shelter_score,
    get_population_pressure,
    get_activity_tendency,
    get_behavior_context,
)
from .ecosystem import (
    VerdantPopulationSample,
    VerdantResourceEvaluator,
    VerdantPopulationDynamics,
    VerdantEcosystemSystem,
    get_population_state,
    get_resource_pressure,
    get_food_availability,
    get_water_availability,
    get_shelter_availability,
    get_sustainability,
    get_population_trend,
    get_recovery_tendency,
    get_expansion_tendency,
)
from .feedback import (
    VerdantEcologicalSignals,
    VerdantVegetationFeedback,
    VerdantHabitatFeedback,
    VerdantWaterFeedback,
    VerdantFeedbackSystem,
    get_ecosystem_state,
    get_ecological_health,
    get_grazing_pressure,
    get_vegetation_stress,
    get_vegetation_recovery,
    get_habitat_pressure,
    get_water_stress,
    get_drought_pressure,
    get_adaptive_response,
    explain_ecosystem,
)

__all__ = [
    'VerdantHooks',
    'VerdantWorldState',
    'VerdantSimulationClock',
    'VerdantWorldQueryBoundary',
    'VerdantStatePersistence',
    'VerdantSystem',
    'VerdantSimulationManager',
    'VerdantBiomeDefinition',
    'VerdantBiomeResolver',
    'VerdantClimateSystem',
    'VerdantWorldSeed',
    'VerdantMoistureState',
    'VerdantWaterSystem',
    'get_soil_moisture',
    'get_surface_water_presence',
    'get_water_proximity',
    'get_water_influence',
    'is_near_water',
    'get_moisture_state',
    'VerdantVegetationState',
    'VerdantEcologySystem',
    'get_vegetation_state',
    'get_growth_potential',
    'get_vegetation_health',
    'get_environmental_stress',
    'get_fertility',
    'get_season_modifier',
    'get_current_season',
    'get_season_progress',
    'is_growth_favorable',
    'VerdantCreatureState',
    'VerdantHabitatEvaluator',
    'VerdantBehaviorContext',
    'VerdantCreatureSystem',
    'get_creature_state',
    'get_habitat_score',
    'get_food_suitability',
    'get_water_access',
    'get_shelter_score',
    'get_population_pressure',
    'get_activity_tendency',
    'get_behavior_context',
    'VerdantPopulationSample',
    'VerdantResourceEvaluator',
    'VerdantPopulationDynamics',
    'VerdantEcosystemSystem',
    'get_population_state',
    'get_resource_pressure',
    'get_food_availability',
    'get_water_availability',
    'get_shelter_availability',
    'get_sustainability',
    'get_population_trend',
    'get_recovery_tendency',
    'get_expansion_tendency',
    'VerdantEcologicalSignals',
    'VerdantVegetationFeedback',
    'VerdantHabitatFeedback',
    'VerdantWaterFeedback',
    'VerdantFeedbackSystem',
    'get_ecosystem_state',
    'get_ecological_health',
    'get_grazing_pressure',
    'get_vegetation_stress',
    'get_vegetation_recovery',
    'get_habitat_pressure',
    'get_water_stress',
    'get_drought_pressure',
    'get_adaptive_response',
    'explain_ecosystem',
    'VERDANT_CONFIG',
    '__version__',
    '__build__',
    '__release_name__',
]
